# Generated by Django 3.1 on 2020-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the teacher.', max_length=100)),
                ('last_name', models.CharField(help_text='First name of the teacher.', max_length=100)),
                ('subject', models.CharField(help_text='Subject which teacher teaches.', max_length=150)),
                ('student', models.ManyToManyField(help_text='Students taught by the teacher', related_name='teacher', to='student.Student')),
            ],
        ),
    ]
