# Generated by Django 3.1 on 2020-08-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
        migrations.CreateModel(
            name='StudentTeacherRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starred', models.BooleanField(default=False, help_text='Whether student is starred by the teacher.')),
                ('date_starred', models.DateTimeField(blank=True, help_text='Date time the student is starred.', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='student_taught',
            field=models.ManyToManyField(help_text='Students taught by the teacher', related_name='teacher', through='teacher.StudentTeacherRelation', to='student.Student'),
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='student_taught',
            new_name='student',
        ),
    ]
