# Generated by Django 3.1 on 2020-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the student.', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the student.', max_length=100)),
                ('dob', models.DateField(help_text='Date of birth.')),
                ('stream', models.CharField(help_text='Field of study.', max_length=100)),
                ('roll_number', models.CharField(help_text='Roll number of student', max_length=10, unique=True)),
            ],
        ),
    ]
